from typing import Protocol

from findr.domain.entities import Credentials


class OAuthProvider(Protocol):
    def build_authorize_url(self, state: str, code_challenge: str) -> str: ...
    def exchange_code(self, code: str, code_verifier: str) -> Credentials: ...
    def refresh(self, refresh_token: str) -> Credentials: ...
    def revoke(self, token: str) -> None: ...
    def get_account_email(self, access_token: str) -> str:
        """The email address of the account these credentials belong to —
        needed to know *which* account got connected."""
        ...
