from typing import Protocol


class SessionStore(Protocol):
    def create(self, user_id: int) -> str: ...
    def get_user_id(self, token: str) -> int | None: ...
    def delete(self, token: str) -> None: ...
