from typing import Protocol

from findr.domain.entities import User


class UserRepository(Protocol):
    def get_by_email(self, email: str) -> User | None: ...
    def get_by_id(self, user_id: int) -> User | None: ...
    def create(self, email: str, password_hash: str) -> User: ...
