from typing import Protocol

from findr.domain.entities import Workspace


class WorkspaceRepository(Protocol):
    def create(self, user_id: int, name: str) -> Workspace: ...
    def get(self, workspace_id: int, user_id: int) -> Workspace | None:
        """None both when missing and when it belongs to another user."""
        ...
    def list_for_user(self, user_id: int) -> list[Workspace]:
        """Sorted by name."""
        ...
    def get_by_name(self, user_id: int, name: str) -> Workspace | None:
        """Case-insensitive."""
        ...
    def rename(self, workspace_id: int, name: str) -> None: ...
    def delete(self, workspace_id: int) -> None: ...
